import { readFileSync, writeFileSync, mkdirSync, existsSync } from 'node:fs';
import { createRequire } from 'node:module';
import { createHash } from 'node:crypto';
import { join, resolve } from 'node:path';
const core = createRequire(import.meta.url)('../dist/store-core.js');
const capture = JSON.parse(readFileSync('docs/source/public-capture.json','utf8'));
const imageRecords = existsSync('docs/product-images.json') ? JSON.parse(readFileSync('docs/product-images.json','utf8')) : [];
const esc = s => String(s ?? '').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const slug = s => s.toLowerCase().normalize('NFKD').replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');
const categories = capture.categories;
const byId = new Map(categories.map(c=>[c.id,c]));
const roots = categories.filter(c=>!byId.has(c.parent));
const route = path => path.endsWith('/') ? path : path + '/';
const versionAssets = html => html.replace(/\b(href|src)="\/?(styles\.css|store\.css|motion\.css|brand\.css|app\.js|store-core\.js|store\.js|motion\.js)(?:\?[^"\s]*)?"/g, (_,attr,file)=>`${attr}="/${file}?v=${createHash('sha256').update(readFileSync(join('dist',file))).digest('hex').slice(0,12)}"`);
function withMotion(html) {
  if (!html.includes('data-motion-control')) html=html.replace(/<button class="menu-toggle"[\s\S]*?<\/button>/,menu=>`<div class="header-controls"><button class="motion-toggle" data-motion-control type="button" aria-label="Pause motion" hidden><svg aria-hidden="true" viewBox="0 0 24 24"><path class="motion-pause-icon" d="M9 5v14M15 5v14"/><path class="motion-play-icon" d="m8 5 11 7-11 7Z"/></svg><span>Pause motion</span></button>${menu}</div>`);
  html=html.replace(/<link\b[^>]*href="\/motion\.css(?:\?[^"\s]*)?"[^>]*>/g,'').replace(/<script\b[^>]*src="\/motion\.js(?:\?[^"\s]*)?"[^>]*><\/script>/g,'');
  html=html.replace(/<link\b[^>]*href="\/brand\.css(?:\?[^"\s]*)?"[^>]*>/g,'');
  return html.replace('</head>','<link rel="stylesheet" href="/motion.css"><link rel="stylesheet" href="/brand.css"></head>').replace('</body>','<script src="/motion.js" defer></script></body>');
}
const money = n => new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(n);
const products = capture.products.map(p=>{
  const category = categories.find(c=>c.name.toLowerCase()===p.category.toLowerCase()) || categories.find(c=>p.sourcePaths.includes(c.path));
  const photo = imageRecords.find(i=>i.id===p.id && i.path);
  return {...p, category:p.category || category?.name || 'Catalog item', categoryId:category?.id || null, path:`/products/${p.id}/`, image:photo?.path || null, width:photo?.width, height:photo?.height};
});
const games = [
  ['magic','Magic: The Gathering',[8,12],'Singles, sealed releases, and the next card for your deck.',/magic_the_gathering|avatar_the_last_airbender|marvel_super_heroes/],
  ['pokemon','Pokémon',[226,385],'Collect your favorites and build your next battle deck.',/pokemon/],
  ['lorcana','Disney Lorcana',[15294,15295],'Explore the Disney Lorcana trading card game.',/lorcana|wilds_unknown/],
  ['onepiece','One Piece',[16481,16476],'Singles and sealed products for your next adventure.',/one_piece|charlotte_katakuri/],
  ['yugioh','Yu-Gi-Oh!',[228,654],'Find cards and sealed products for your next duel.',/yugioh/],
  ['riftbound','Riftbound',[16695,16681],'League of Legends comes to the table.',/riftbound/],
  ['gundam','Gundam',[16664,16644],'Build your strategy with the Gundam Card Game.',/gundam|steel_requiem/],
  ['starwars','Star Wars: Unlimited',[16317,16313],'Build a deck from a galaxy of possibilities.',/star_wars_unlimited/],
  ['union','Union Arena',[16563,16564],'Favorite worlds. A new matchup.',/union_arena|kaiju_no_8/],
  ['digimon','Digimon',[15024],'Starter decks and sealed products for the Digimon Card Game.',/digimon/],
  ['palworld','Palworld',[16801],'Explore the Palworld Official Card Game.',/palworld/],
  ['supplies','Dice & deck gear',[5242,1542,16733],'Protect your collection. Equip your table.',/accessories|gaming_dice|dn_binder/],
  ['miniatures','Miniature games',[16746],'Warhammer, Marvel Crisis Protocol, and your next tabletop project.',/games_workshop|marvel_crisis_protocol/],
  ['paints','Paints & hobby supplies',[16505],'Paints, brushes, and tools for the workbench.',/army_painter|games_workshop_paints/]
];
const dims = JSON.parse(readFileSync('docs/game-images.json','utf8'));
const photo = id => {const d=dims.find(x=>x.slug===id); return `<img src="/assets/games/${id}.webp" alt="${esc(d?.alt || `${games.find(g=>g[0]===id)?.[1]} representative product packaging`)}" width="${d?.web_width || d?.width || 640}" height="${d?.web_height || d?.height || 640}" loading="lazy" decoding="async">`;};
const notice = '<div class="preview-notice">Private preview · Product samples, not live stock. No orders or payments.</div>';
const brand = '<a class="brand" href="/" aria-label="Duelers Guild home"><img src="/assets/guild-mark.png" alt="" width="64" height="64"><span>Duelers<br>Guild<span class="brand-location">A place for players.</span></span></a>';
const header = `<header class="site-header"><div class="header-inner wrap">${brand}<button class="menu-toggle" aria-controls="site-nav" aria-expanded="false" type="button"><span>Menu</span><span class="menu-lines" aria-hidden="true"></span></button><nav id="site-nav" aria-label="Main navigation"><a href="/shop/">The shop</a><a href="/play/">Come play</a><a href="/sell/">Sell cards</a><a href="/visit/">Find us</a><a href="/account/">Account</a><a class="button button-small" href="/cart/"><svg aria-hidden="true" viewBox="0 0 24 24"><path d="M6 7h12l2 14H4L6 7Zm3 0V5a3 3 0 0 1 6 0v2"/></svg>Cart <span data-cart-count>0</span></a></nav></div><div class="utility-bar"><nav class="wrap" aria-label="Player navigation"><a href="/search/">Search cards & products</a><a href="/deckbuilder/">Deckbuilder</a><a href="/buylist/">Buylist</a><a href="/wishlist/">Saved products</a><a href="/events/">Events</a><a href="/catalog/">All sets & categories</a></nav></div></header>${notice}`;
const footer = `<footer class="site-footer"><div class="wrap footer-top">${brand}<div class="footer-links"><div><span>Explore</span><a href="/shop/">All games & gear</a><a href="/catalog/">All categories & sets</a><a href="/events/">Events</a><a href="/about/">About the Guild</a><a href="/gallery/">Gallery</a><a href="/news/">News</a><a href="/visit/">Visit & hours</a></div><div><span>Player tools</span><a href="/deckbuilder/">Deckbuilder</a><a href="/buylist/">Buylist builder</a><a href="/condition-guide/">Card condition guide</a><a href="/wishlist/">Saved products</a><a href="/account/">Store account</a><a href="/sitemap/">Every page</a></div><div><span>Connect</span><a href="/contact/">Contact the Guild</a><a href="https://discord.gg/YCZx9CMeDd">Discord</a><a href="https://www.facebook.com/DuelersguildTracy">Facebook</a><a href="https://www.instagram.com/duelersguild104/">Instagram</a><a href="mailto:support@duelersguild.com">Email the Guild</a></div></div></div><div class="wrap footer-bottom"><p>© 2026 Duelers Guild</p><div><a href="/policies/">Store policies</a><a href="/terms/">Terms</a><a href="/privacy/">Privacy</a></div></div></footer>`;
const head = readFileSync('dist/index.html','utf8').match(/<head>([\s\S]*?)<\/head>/)[1].replace(/href="(assets\/|styles.css)/g,'href="/$1').replace(/<link\b[^>]*href="\/store\.css(?:\?[^"\s]*)?"[^>]*>/g,'');
const manifest = [];
function page(path,title,body,type='content',description=title) {
  const canonical = route(path);
  const file = canonical==='/'?'dist/index.html':join('dist',canonical,'index.html');
  const pageHead=head.replace(/<title>[\s\S]*?<\/title>/,`<title>${esc(title)} | Duelers Guild</title>`).replace(/(<meta name="description" content=")[^"]*/,'$1'+esc(description)).replace(/(<meta property="og:title" content=")[^"]*/,'$1'+esc(title+' | Duelers Guild')).replace(/(<meta property="og:description" content=")[^"]*/,'$1'+esc(description));
  const html=`<!doctype html><html lang="en"><head>${pageHead}<link rel="stylesheet" href="/store.css"></head><body data-page="${type}"><a class="skip-link" href="#main">Skip to content</a>${header}<main id="main" class="page-main">${body}</main>${footer}<div class="store-toast" role="status" aria-live="polite"></div><script src="/store-core.js" defer></script><script src="/app.js" defer></script><script src="/store.js" defer></script></body></html>`;
  mkdirSync(resolve(file,'..'),{recursive:true});writeFileSync(file,versionAssets(withMotion(html)));
  manifest.push({path:canonical,title,type});
}
const link = (path,label,style='button')=>`<a class="${style}" href="${route(path)}">${esc(label)}</a>`;
const title = (name,description='')=>`<div class="page-heading"><h1>${esc(name)}</h1>${description?`<p>${esc(description)}</p>`:''}</div>`;
const panel = (heading,content)=>`<section class="text-panel"><h2>${esc(heading)}</h2>${content}</section>`;
const breadcrumbs = trail=>`<nav class="breadcrumbs" aria-label="Breadcrumb"><a href="/">Home</a>${trail.map(([p,l])=>`<span aria-hidden="true">/</span><a href="${route(p)}">${esc(l)}</a>`).join('')}</nav>`;
const card = p=>`<article class="product-card"><a class="product-photo" href="${p.path}">${p.image?`<img src="${p.image}" alt="${esc(p.name)}" width="${p.width}" height="${p.height}" loading="lazy" decoding="async">`:'<span class="photo-unavailable">Product photo unavailable</span>'}</a><div class="product-meta"><p class="product-category">${esc(p.category)}</p><h3><a href="${p.path}">${esc(p.name)}</a></h3><p class="price">${p.price!=null?money(p.price):'Price not captured'} <span>Sample price</span></p><div class="product-actions">${link(p.path,'View product','button button-small button-outline')}<button class="save-product" data-save="${p.id}" aria-pressed="false" type="button">Save</button></div></div></article>`;
const grid = list=>`<div class="product-grid">${list.map(card).join('')}</div>`;
const empty = (heading,text)=>`<div class="empty-state"><h2>${esc(heading)}</h2><p>${esc(text)}</p>${link('/contact/','Ask the Guild','button button-outline')}</div>`;
const sourceNote='<p class="source-note">Product examples and prices captured September 16, 2026. Not a full inventory export; stock, variants and final prices are unverified.</p>';
const searchForm=(id='query',action='/search/')=>`<form class="inventory-search" action="${action}" method="get"><label for="${id}">Find a card, set, or product</label><div><input id="${id}" type="search" name="q" placeholder="Card name, set, or product…" autocomplete="off"><button class="button" type="submit">Search</button></div></form>`;
const catLinks = list=>`<ul class="category-list">${list.map(c=>`<li data-list-item><a href="${route(c.path)}">${esc(c.name)}<span>${categories.filter(x=>x.parent===c.id).length ? 'Browse sets' : 'View category'}</span></a></li>`).join('')}</ul>`;
const listFilter = id=>`<label class="filter-label" for="${id}">Filter this list</label><input class="list-filter" id="${id}" type="search" placeholder="Type a set or category…" autocomplete="off" data-list-filter><p class="filter-status" aria-live="polite" data-filter-status></p>`;
const toolForm=mode=>`${title(mode==='buylist'?'Build your sell list.':'Find your deck.','Paste one card per line. Include quantities such as 3 Forest or 3x Forest.')}<div class="tool-grid"><form class="tool-form" data-list-tool="${mode}"><label for="card-list">${mode==='buylist'?'Cards to sell':'Your decklist'}</label><textarea id="card-list" name="cards" rows="12" placeholder="3 Forest&#10;2x Catalyst Stone…" autocomplete="off" maxlength="30000" required></textarea><p class="field-help">Saved only on this device. Card names are matched against the sample catalog; select the exact printing when live inventory is connected.</p><div class="tool-actions"><button class="button" type="submit">${mode==='buylist'?'Build sell list':'Find matching cards'}</button><button class="button button-outline" data-export-list type="button">Download list</button></div><p data-list-feedback role="status" aria-live="polite"></p></form><aside class="text-panel"><h2>${mode==='buylist'?'Before you sell':'Know your list'}</h2><p>${mode==='buylist'?'Cash and store-credit offers require the Guild’s verified buylist feed. This preview does not quote offers or submit a sale.':'Sample matches are not stock confirmations. This tool does not check deck legality or reserve cards.'}</p>${link('/condition-guide/','Card condition guide','text-link')}${link(mode==='buylist'?'/sell/review/':'/cart/',mode==='buylist'?'Review your sell list':'View review cart','text-link')}</aside></div><section class="tool-results" aria-label="Card list results" data-list-results></section>`;

// Mechanical home link migration; keep the approved full-bleed design and directory intact.
let home = readFileSync('dist/index.html','utf8');
const mappings = new Map([['/','/shop/'],['/products/search','/search/'],['/products/multi_search','/deckbuilder/'],['/buylist/multi_search','/buylist/'],['/card_condition_guide','/condition-guide/'],['/user/login','/account/'],['/store_policies','/policies/'],['/terms_and_conditions','/terms/']]);
home=home.replace(/https:\/\/www\.duelersguild\.com([^"\s<]*)/g,(_,path)=>mappings.get(path)|| (path.startsWith('/products/search?')?'/search/'+path.slice('/products/search'.length):route(path)));
home=home.replace(/<header class="site-header">[\s\S]*?<\/header>(?:<div class="preview-notice">[\s\S]*?<\/div>)?/,header);
home=home.replace(/<footer class="site-footer">[\s\S]*?<\/footer>/,footer);
if(!/href="\/store\.css(?:\?[^"\s]*)?"/.test(home)) home=home.replace('</head>','<link rel="stylesheet" href="/store.css"></head>');
if(!/src="\/store\.js(?:\?[^"\s]*)?"/.test(home)) home=home.replace('</body>','<div class="store-toast" role="status" aria-live="polite"></div><script src="/store-core.js" defer></script><script src="/store.js" defer></script></body>');
home=home.replace('Search inventory <svg','Search <svg').replace('live inventory','sample catalog');
home=home.replace('Product photos are examples. Check inventory for current availability.','Product photos are examples. This private preview does not show live availability.');
home=home.replace('The buylist shows the Guild’s buying prices. Find the cards and versions that match your collection.','The new builder organizes your list. Cash and store-credit offers need the Guild’s live buylist connection.');
home=home.replace('Check cash and store-credit offers for the cards you’re ready to part with.','Organize the cards you’re ready to part with. Ask the Guild about cash and store-credit offers.');
home=home.replace('Paste a decklist to find matching cards in the store’s inventory.','Paste a decklist to find matching cards in the sample catalog.');
home=home.replace('<h3>Check the offers.</h3>','<h3>Confirm the offers.</h3>');
home=home.replace('Join the Discord <svg','Join the Discord <svg');
if(!home.includes('View events</a>')) home=home.replace('<p class="play-socials">','<a class="text-link" href="/events/">View events</a><p class="play-socials">');
home=home.replace(new RegExp(`(<article class="game-entry (${games.map(g=>g[0]).join('|')})"[^>]*>[\\s\\S]*?<h3>)([\\s\\S]*?)(</h3>)`,'g'),(_,start,id,name,end)=>start+(name.startsWith('<a ')?name:`<a href="/shop/${id}/">${name}</a>`)+end);
writeFileSync('dist/index.html',versionAssets(withMotion(home)));manifest.push({path:'/',title:'Duelers Guild',type:'home'});

const directory = home.match(/<div class="directory" aria-label="Game directory">([\s\S]*?)<\/div>\s*<p class="image-note">/)[1].replace(/src="assets\//g,'src="/assets/');
page('/shop/','All games & gear',`<div class="wrap page-space">${breadcrumbs([['/shop/','Shop']])}${title('Find your next game.','Trading cards, tabletop games, and gear for the table.')}${searchForm()}<div class="directory-toolbar"><div class="directory-filters" role="group" aria-label="Filter game directory"><button type="button" data-filter="all" aria-pressed="true">All games & gear</button><button type="button" data-filter="cards" aria-pressed="false">Trading cards</button><button type="button" data-filter="tabletop" aria-pressed="false">Tabletop & supplies</button></div><p id="directory-status" aria-live="polite">14 categories</p></div><div class="directory">${directory}</div><div class="collection-bar">${link('/catalog/','Browse every category & set')}${link('/search/','View product samples','button button-outline')}</div></div>`,'shop');
page('/catalog/','All categories & sets',`<div class="wrap page-space">${breadcrumbs([['/shop/','Shop'],['/catalog/','Categories']])}${title('The whole collection.','Browse the complete category structure from the Guild’s public catalog.')}${listFilter('category-filter')}${catLinks(roots)}<div class="collection-bar">${link('/sitemap/','Find a specific set','button button-outline')}</div>${sourceNote}</div>`,'catalog');
for(const c of categories) {
  const children=categories.filter(x=>x.parent===c.id);
  const trail=[];let cursor=c;const seen=new Set();
  while(cursor && !seen.has(cursor.id)){seen.add(cursor.id);trail.unshift([cursor.path,cursor.name]);cursor=byId.get(cursor.parent);}
  const examples=products.filter(p=>core.descends(p.categoryId,c.id,categories));
  page(c.path,c.name,`<div class="wrap page-space">${breadcrumbs([['/shop/','Shop'],...trail])}${title(c.name)}${searchForm()}<div class="catalog-layout"><aside class="catalog-sidebar"><h2>${children.length?'Browse this collection':'In this collection'}</h2>${children.length?listFilter('set-filter')+catLinks(children):`<p>Use search to find a card or product, or explore the parent collection.</p>${link(trail.length>1?trail.at(-2)[0]:'/catalog/','Back to collection','text-link')}`}</aside><section class="catalog-products" aria-label="Product samples"><div class="results-heading"><h2>Product samples</h2><p>${examples.length} captured examples</p></div>${examples.length?grid(examples):empty('Inventory connection needed','This category page is ready, but its product records have not been imported. This does not mean the Guild is out of stock. Search the sample catalog or ask the staff about availability.')}${sourceNote}</section></div></div>`,'category');
}
for(const [id,name,ids,description,pattern] of games) {
  const examples=products.filter(p=>pattern.test(p.legacyPath) || ids.some(ancestor=>core.descends(p.categoryId,ancestor,categories)));
  page(`/shop/${id}/`,name,`<div class="wrap page-space">${breadcrumbs([['/shop/','Shop'],[`/shop/${id}/`,name]])}<section class="game-hub"><div>${title(name,description)}${catLinks(ids.map(i=>byId.get(i)).filter(Boolean))}</div><div class="hub-photo">${photo(id)}</div></section>${searchForm()}<div class="results-heading"><h2>Explore the catalog</h2><p>${examples.length} product samples</p></div>${examples.length?grid(examples):empty('Explore the collections above','Use the category and set pages to browse this game. Live product records and current availability require the store connection.')}${sourceNote}</div>`,'game');
}
function productPage(p,path) {
  const category=byId.get(p.categoryId);
  page(path,p.name,`<div class="wrap page-space">${breadcrumbs([['/shop/','Shop'],...(category?[[category.path,category.name]]:[]),[p.path,p.name]])}<div class="product-detail"><div class="detail-photo">${p.image?`<img src="${p.image}" alt="${esc(p.name)}" width="${p.width}" height="${p.height}" fetchpriority="high">`:'<p>Product photo unavailable. No substitute image is shown.</p>'}</div><div class="detail-copy"><p class="product-category">${esc(p.category)}</p><h1>${esc(p.name)}</h1><p class="detail-price">${p.price!=null?money(p.price):'Price not captured'} <span>Sample price</span></p><p class="stock-note">Live stock and card variants are not connected.</p><p>This is a real product example from the Guild’s public catalog. Condition, printing, foil treatment and availability must be confirmed before purchase.</p><form data-add-cart="${p.id}" class="add-cart"><label for="quantity">Quantity for review</label><div><input id="quantity" name="quantity" type="number" min="1" max="99" value="1" required inputmode="numeric"><button class="button" type="submit">Add to review cart</button></div><p class="field-help">Saved on this device only. This does not place an order or reserve stock.</p></form><button type="button" class="button button-outline" data-save="${p.id}" aria-pressed="false">Save product</button><div class="detail-links">${link('/condition-guide/','Understand card condition','text-link')}${link('/policies/','Returns & store policies','text-link')}${link('/contact/','Ask about this product','text-link')}</div>${sourceNote}</div></div>${panel('Product details',`<dl class="product-facts"><div><dt>Catalog reference</dt><dd>${p.id}</dd></div><div><dt>Collection</dt><dd>${esc(p.category)}</dd></div><div><dt>Availability</dt><dd>Requires live inventory connection</dd></div><div><dt>Pickup & delivery</dt><dd>Methods and rates require owner confirmation</dd></div></dl>`)}</div>`,'product');
}
for(const p of products){productPage(p,p.path);productPage(p,p.legacyPath);}
for(const p of capture.buylistProducts || []) page(p.path,p.name,`<div class="wrap page-space">${breadcrumbs([['/sell/','Sell cards'],['/buylist/','Buylist'],[p.path,p.name]])}${title(p.name)}<div class="editorial-grid">${panel('Prepare this card for selling',`<p>Catalog reference ${p.id}. Confirm the exact printing, foil treatment and condition with the Guild before selling.</p>${link('/buylist/','Add cards to your sell list')}${link('/condition-guide/','Check card condition','text-link')}`)}${panel('Live offers are not connected','<p>Cash prices, store-credit prices and buying limits require the Guild’s verified buylist feed. No offer or sale is being created in this preview.</p>'+link('/contact/','Ask the Guild','button button-outline'))}</div></div>`,'buylist-product');
const contact=`<div class="contact-lines"><a href="tel:2096994106">(209) 699-4106</a><a href="mailto:support@duelersguild.com">support@duelersguild.com</a><p>104 W 11th Street<br>Tracy, CA 95376</p></div>`;
const social=`<div class="tool-actions">${link('https://discord.gg/YCZx9CMeDd','Join the Discord')}${link('https://www.facebook.com/DuelersguildTracy','Facebook','button button-outline')}${link('https://www.instagram.com/duelersguild104/','Instagram','button button-outline')}</div>`;
const pages={
 '/about/':['About the Guild',`${title('Your local guild.','Trading cards, tabletop games, and community in downtown Tracy.')}<div class="editorial-grid"><div>${panel('A place for players','<p>The Guild brings collectors, card players, miniature gamers and newcomers together. Pick up supplies, ask a question, or find someone to play.</p>')}${panel('Find your table','<p>Explore trading card games, miniature games, gaming dice and hobby supplies. Ask the staff about casual play and current tournaments.</p>'+link('/play/','Play at the Guild','text-link'))}</div><aside class="text-panel"><h2>Come by.</h2>${contact}${link('/visit/','Plan your visit')}</aside></div>`],
 '/play/':['Play & community',`${title('Good games. Better company.','Bring your deck, meet other players, and find your table.')}<div class="feature-band"><div><h2>Play at the Guild</h2><p>Tournaments, casual matches and tabletop games. New to a game? Ask the staff for help getting started.</p>${link('/events/','Explore events','button button-light')}</div><div><h2>Find your people</h2><p>Connect with local players and ask about upcoming games on the Guild’s community channels.</p>${social}</div></div>${panel('Before you head over','<p>Call the store to confirm today’s hours, available tables, event formats and entry details. Closed Wednesdays.</p>'+link('/visit/','Visit the store','text-link'))}`],
 '/events/':['Events',`${title('Find your next matchup.','Tournaments and casual play at the Guild.')}<div class="editorial-grid">${panel('Upcoming dates','<p>A verified event schedule has not been supplied for the new site. No dates, entry fees or seat availability are being invented.</p><p>Ask the Guild for the current schedule and registration details.</p>'+contact)}${panel('Meet the community','<p>Find other players, ask about formats, and get current event announcements.</p>'+social)}</div>${panel('Games at the Guild',catLinks(roots.filter(c=>/singles|sealed|miniature|marvel/i.test(c.name))))}`],
 '/sell/':['Sell your cards',`${title('A new chapter for your collection.','Organize your cards before talking with the Guild.')}<ol class="full-sell-steps"><li><h2>Make your list.</h2><p>Add card names and quantities. The new builder keeps your list on this device.</p>${link('/buylist/','Open buylist builder')}</li><li><h2>Check the condition.</h2><p>Match the card version and review the five condition grades.</p>${link('/condition-guide/','Read the condition guide','button button-outline')}</li><li><h2>Talk with the Guild.</h2><p>Cash and store-credit offers, acceptance and selling instructions require the Guild’s verified buylist connection.</p>${link('/contact/','Contact the staff','button button-outline')}</li></ol>`],
 '/deckbuilder/':['Deckbuilder',toolForm('deck')],
 '/buylist/':['Buylist builder',toolForm('buylist')],
 '/sell/review/':['Review your sell list',`${title('Your sell list.','Saved on this device. No sale has been submitted.')}<div data-sell-review></div>${panel('Get an actual offer','<p>Final grading, cash offers, store-credit offers and buying limits must come from the Guild. The preview does not assign values to your cards.</p>'+link('/contact/','Talk to the Guild'))}`],
 '/visit/':['Visit & hours',`${title('See you at the Guild.','104 W 11th Street, Tracy, California.')}<div class="editorial-grid">${panel('Downtown Tracy',contact+`<a class="button" href="https://maps.google.com/?q=104%20W%2011th%20Street%20Tracy%20CA%2095376">Get directions</a>`)}${panel('Plan your visit','<p>Closed Wednesdays. The public store pages show conflicting opening schedules, so call for today’s hours before making the trip.</p><a class="button button-outline" href="tel:2096994106">Call for today’s hours</a>'+link('/events/','Explore events','text-link'))}</div>`],
 '/contact/':['Contact the Guild',`${title('Ask the Guild.','Product questions, card selling, events, or planning a visit.')}<div class="editorial-grid">${panel('Talk with the staff',contact)}${panel('Start with the right place',`<div class="link-stack">${link('/condition-guide/','Card condition questions','text-link')}${link('/policies/','Returns & refunds','text-link')}${link('/events/','Upcoming games','text-link')}${link('/visit/','Directions & hours','text-link')}</div><p>The preview does not send support forms. Email opens your own email app.</p><a class="button" href="mailto:support@duelersguild.com">Write an email</a>`)}</div>${panel('Community channels',social)}`],
 '/gallery/':['Gallery',`${title('Games & gear.','Real product packaging, not photographs of the store.')}<p class="intro-note">Verified store and event photographs have not been supplied. Until then, explore the game-and-gear imagery used throughout the new site.</p><div class="gallery-grid">${games.map(([id,name])=>`<figure><a href="/shop/${id}/">${photo(id)}</a><figcaption><a href="/shop/${id}/">${esc(name)}</a></figcaption></figure>`).join('')}</div>`],
 '/news/':['Guild news',`${title('News from the Guild.')}<div class="editorial-grid">${panel('Latest announcements','<p>Verified news articles have not been supplied for this preview. For current announcements, use the Guild’s community channels.</p>'+social)}${panel('Looking for event details?','<p>Confirm dates, game formats and entry requirements with the staff.</p>'+link('/events/','Events at the Guild'))}</div>`],
 '/condition-guide/':['Card condition guide',`${title('Know your card condition.','A guide to the Guild’s five grades. Staff inspection determines final grading.')}<div class="condition-page">${[['NM','Near Mint','Minimal handling wear, with surfaces, corners and edges close to fresh out of the pack.'],['LP','Lightly Played','Slight edge or corner wear and minor scratches, without major defects. Foils may show slight wear or fading.'],['MP','Moderately Played','Noticeable wear such as scratches, border wear, creases, fading or light damage.'],['HP','Heavily Played','Heavy wear, significant creasing, folding, water damage, whitening or worn borders.'],['D','Damaged','Major bends, tears, writing, inking or severe wear. A sleeve does not necessarily make the card tournament suitable.']].map(([code,name,text])=>`<article><span>${code}</span><div><h2>${name}</h2><p>${text}</p></div></article>`).join('')}</div>${panel('Not sure how to grade a card?','<p>Ask the Guild before selling or ordering a particular condition.</p>'+link('/contact/','Ask the staff','button button-outline'))}`],
 '/policies/':['Store policies',`${title('Store policies.','Source-derived summary for owner review before launch.')}<div class="prose">${panel('Returns','<p>The current policy allows most new, unopened products sold and fulfilled by the Guild to be returned within 30 days of delivery for the purchase-price refund. Wrong, damaged or defective items may qualify for return; the Guild states it pays return shipping for its own errors.</p>')}${panel('Refunds','<p>Returned items are inspected before a refund is issued. The current policy allows up to four weeks overall, including the return journey, processing and bank timing, with email notification when the refund is issued.</p>')}${panel('Arrange a return','<p>Contact the Guild with your order reference and the problem before returning an item. Product-specific exceptions and the final launch policy need owner confirmation.</p>'+contact)}${link('/privacy/','Privacy information','text-link')}${link('/terms/','Terms & conditions','text-link')}</div>`],
 '/terms/':['Terms & conditions',`${title('Terms & conditions.','Source-derived summary for owner review before launch.')}<div class="prose">${panel('Using the store','<p>The current store terms describe use of the site as acceptance of its conditions and privacy policy. The Guild may update those conditions; the current version should be reviewed before using the live store.</p>')}${panel('Order acceptance','<p>Placing an order does not itself mean the Guild has accepted it. The current terms allow refusal for inventory shortages, pricing errors or payment concerns. Missing items or unreceived orders should be reported within 30 days.</p>')}${panel('This private preview','<p>This site does not currently accept orders, payments, customer registration or buylist submissions. Review carts and lists stay on your device. These summaries do not create new or approved terms for the store.</p>')}${link('/policies/','Store policies','text-link')}${link('/privacy/','Privacy information','text-link')}</div>`],
 '/privacy/':['Privacy',`${title('Privacy.','How this private preview handles information.')}<div class="prose">${panel('On this device','<p>Review-cart items, saved products, card lists and your motion preference use browser storage on this device. They are not shared across devices or sent to the Guild. You can remove individual saved items, edit lists or clear site data through your browser settings.</p>')}${panel('Accounts & payments','<p>This preview does not accept passwords, payment details, customer addresses or account registration. The existing storefront’s customer-data practices need to be reviewed with the owner before connecting real services.</p>')}${panel('Outside links','<p>Maps, Discord and social links open third-party services with their own policies. Email and telephone links open your own apps. No analytics or advertising scripts were added to this site.</p>')}${panel('Questions',contact)}</div>`],
 '/search/':['Search products',`${title('Find a card or product.','Search real examples from the public catalog, not live inventory.')}<form class="search-controls" data-search><label for="product-query">Search</label><div class="search-row"><input id="product-query" name="q" type="search" autocomplete="off" placeholder="Card, set, or product…"><button class="button" type="submit">Search</button></div><div class="search-options"><label for="sort">Sort<select id="sort" name="sort"><option value="name">Name</option><option value="price-asc">Sample price: low to high</option><option value="price-desc">Sample price: high to low</option></select></label>${link('/advanced-search/','Advanced search','text-link')}</div></form><p data-search-status role="status" aria-live="polite"></p><div data-search-results></div>${sourceNote}`,'search'],
 '/advanced-search/':['Advanced search',`${title('Narrow your search.','Filter the sample catalog by name, collection and captured price.')}<form class="search-controls" data-search><label for="product-query">Card or product</label><input id="product-query" name="q" type="search" autocomplete="off" placeholder="Name or set…"><div class="search-options"><label for="min-price">Minimum sample price<input id="min-price" name="min" type="number" min="0" step="0.01" inputmode="decimal"></label><label for="max-price">Maximum sample price<input id="max-price" name="max" type="number" min="0" step="0.01" inputmode="decimal"></label><label for="collection">Collection<select id="collection" name="category"><option value="">All captured collections</option>${[...new Set(products.map(p=>p.categoryId).filter(Boolean))].map(id=>`<option value="${id}">${esc(byId.get(id).name)}</option>`).join('')}</select></label><label for="sort">Sort<select id="sort" name="sort"><option value="name">Name</option><option value="price-asc">Sample price: low to high</option><option value="price-desc">Sample price: high to low</option></select></label></div><button class="button" type="submit">Search products</button></form><p data-search-status role="status" aria-live="polite"></p><div data-search-results></div>${sourceNote}`,'search'],
 '/cart/':['Review cart',`${title('Your review cart.','Product samples saved on this device. Nothing has been ordered or reserved.')}<div data-cart></div>`,'cart'],
 '/checkout/':['Checkout',`${title('Review before checkout.','This preview cannot place orders or take payments.')}<div class="editorial-grid"><div data-checkout></div><aside class="text-panel"><h2>Live checkout is not connected.</h2><p>Stock checks, card variants, pickup and shipping options, taxes, payment processing and order confirmation need the Guild’s store connection.</p><button class="button" type="button" disabled>Payment unavailable in preview</button><p class="field-help">No payment or customer details are collected here.</p>${link('/cart/','Back to review cart','text-link')}${link('/policies/','Store policies','text-link')}</aside></div>`,'checkout'],
 '/wishlist/':['Saved products',`${title('Keep it on your radar.','Saved products stay on this device. They are not stock reservations.')}<div data-wishlist></div>`,'wishlist'],
 '/account/':['Store account',`${title('Your store account.')}<div class="editorial-grid">${panel('Sign-in is not connected','<p>Existing customers and orders are managed in the store system. This preview does not accept passwords or access customer records.</p><button class="button" type="button" disabled>Sign-in unavailable in preview</button><div class="link-stack">'+link('/account/register/','Create an account','text-link')+link('/account/reset-password/','Password reset','text-link')+link('/account/orders/','Order history','text-link')+link('/account/profile/','Profile & addresses','text-link')+'</div>')}${panel('Browse without signing in','<p>You can explore every category, save products and build a review cart without an account.</p>'+link('/wishlist/','Saved products','text-link')+link('/cart/','Review cart','text-link')+link('/shop/','Find your game'))}</div>`],
 '/account/register/':['Create an account',`${title('Join the Guild online.')}<div class="prose">${panel('Customer registration needs the store connection','<p>A real account needs verified registration, email confirmation and secure password handling. This preview does not collect registration details or create accounts.</p><button class="button" type="button" disabled>Registration unavailable in preview</button>'+link('/account/','Back to account','text-link'))}</div>`],
 '/account/reset-password/':['Password reset',`${title('Reset your password.')}<div class="prose">${panel('Password reset is not connected','<p>No reset email can be sent from this preview. Contact the Guild if you need help with your existing store account. Do not send your password by email.</p>'+contact+link('/account/','Back to account','text-link'))}</div>`],
 '/account/orders/':['Order history',`${title('Your orders.')}<div class="prose">${panel('Customer orders need secure sign-in','<p>No customer orders are imported or displayed in this preview. Once the store connection is approved, this page will use authenticated order records—not public or sample customer data.</p>'+link('/account/','Store account','button button-outline'))}</div>`],
 '/account/profile/':['Profile & addresses',`${title('Profile & addresses.')}<div class="prose">${panel('Your details stay private','<p>Customer profiles and saved addresses require a secure account connection. The preview does not collect, store or display this information.</p>'+link('/account/','Store account','button button-outline'))}</div>`],
 '/preorders/':['Preorders',`${title('What’s next at the Guild.')}<div class="prose">${panel('Confirm upcoming releases','<p>Verified preorder listings and release dates have not been imported. Contact the Guild for current preorder options. No release or stock promise is made by this preview.</p>'+contact+link('/shop/','Explore games','button button-outline'))}</div>`]
};
for(const [path,[name,body,type]] of Object.entries(pages))page(path,name,`<div class="wrap page-space">${breadcrumbs([[path,name]])}${body}</div>`,type||'content');
const aliases = {'/about':'/about/','/contact_us':'/contact/','/card_condition_guide':'/condition-guide/','/store_policies':'/policies/','/terms_and_conditions':'/terms/','/photo_gallery':'/gallery/','/news/list':'/news/','/advanced_search':'/advanced-search/','/products/search':'/search/','/products/multi_search':'/deckbuilder/','/buylist/multi_search':'/buylist/','/buy_orders/show':'/sell/review/','/user/login':'/account/','/user/signup':'/account/register/','/user/forgot_password':'/account/reset-password/','/user/forgot':'/account/reset-password/','/checkout/cart':'/cart/','/checkout/proceed_to_checkout':'/checkout/','/catalog/t/tcg-promotion-page':'/shop/'};
for(const [alias,target] of Object.entries(aliases))if(route(alias)!==target){const html=readFileSync(join('dist',target,'index.html'),'utf8');const file=join('dist',alias,'index.html');mkdirSync(resolve(file,'..'),{recursive:true});writeFileSync(file,html);manifest.push({path:route(alias),title:manifest.find(x=>x.path===target)?.title||target,type:'legacy-local'});}
const snapshot={capturedAt:capture.capturedAt,completeness:capture.completeness,products:products.map(({imageUrl,sourcePaths,...p})=>p)};
writeFileSync('dist/catalog-data.json',JSON.stringify(snapshot));
page('/sitemap/','Every page',`<div class="wrap page-space">${breadcrumbs([['/sitemap/','Every page']])}${title('Every part of the Guild.','Find a page, game category, set, or captured product. All store destinations stay on this site.')}${listFilter('page-filter')}<h2 class="index-heading">Store pages & game hubs</h2><ul class="category-list">${manifest.filter(p=>!['category','product','legacy-local'].includes(p.type)).map(p=>`<li data-list-item><a href="${p.path}">${esc(p.title)}<span>View page</span></a></li>`).join('')}</ul><h2 class="index-heading">All 1,707 catalog categories & sets</h2>${catLinks(categories)}<h2 class="index-heading">Captured products</h2><ul class="category-list">${products.map(p=>`<li data-list-item><a href="${p.path}">${esc(p.name)}<span>${esc(p.category)}</span></a></li>`).join('')}</ul></div>`,'sitemap');
page('/not-found/','Page not found',`<div class="wrap page-space">${title('That page isn’t here.','Find your way back to a game, product, or store page.')}<div class="tool-actions">${link('/shop/','Browse games')}${link('/sitemap/','Find any page','button button-outline')}</div>${searchForm()}</div>`,'not-found');
writeFileSync('dist/404.html',readFileSync('dist/not-found/index.html','utf8'));
writeFileSync('docs/routes.json',JSON.stringify({capturedAt:capture.capturedAt,categoryPages:categories.length,productRecords:products.length,integration:'Private preview, no real transaction or account connection',routes:manifest},null,2));
console.log(JSON.stringify({pages:manifest.length,categories:categories.length,productRecords:products.length,productPhotos:products.filter(p=>p.image).length,oldStoreHandoffs:0}));
